// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShuttleBook.Infrastructure.Data;

#nullable disable

namespace ShuttleBook.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ShuttleBookDbContext))]
    [Migration("20261007150835_F07FixedSeries")]
    partial class F07FixedSeries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShuttleBook.Infrastructure.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AllocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("allocation_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("amount");

                    b.Property<int>("BookingBlockMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("booking_block_minutes");

                    b.Property<string>("BookingNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("booking_no");

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("booking_type");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uuid")
                        .HasColumnName("court_id");

                    b.Property<string>("CourtName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("court_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<int>("HoldMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("hold_minutes");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date")
                        .HasColumnName("local_date");

                    b.Property<TimeOnly>("LocalEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("local_end");

                    b.Property<TimeOnly>("LocalStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("local_start");

                    b.Property<int>("MinimumBookingMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_booking_minutes");

                    b.Property<DateTimeOffset>("PaymentDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_deadline");

                    b.Property<Guid>("PaymentScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_scope_id");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<string>("Slots")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("slots");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("venue_name");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AllocationId")
                        .IsUnique();

                    b.HasIndex("BookingNo")
                        .IsUnique();

                    b.HasIndex("PaymentScopeId");

                    b.HasIndex("AllocationId", "CourtId");

                    b.HasIndex("CourtId", "VenueId");

                    b.HasIndex("CustomerId", "Id");

                    b.HasIndex("SeriesId", "LocalDate")
                        .IsUnique()
                        .HasFilter("series_id IS NOT NULL");

                    b.HasIndex("Status", "PaymentDeadline");

                    b.HasIndex("SeriesId", "CustomerId", "VenueId", "CourtId");

                    b.HasIndex("VenueId", "Status", "LocalDate", "Id");

                    b.ToTable("bookings", null, t =>
                        {
                            t.HasCheckConstraint("ck_booking_grid", "MOD(EXTRACT(EPOCH FROM (ends_at-starts_at))::bigint,1800)=0 AND EXTRACT(SECOND FROM starts_at)=0 AND EXTRACT(SECOND FROM ends_at)=0");

                            t.HasCheckConstraint("ck_booking_payment_scope", "payment_scope_id = COALESCE(series_id,id)");

                            t.HasCheckConstraint("ck_booking_valid", "ends_at > starts_at AND amount >= 0 AND version > 0 AND hold_minutes BETWEEN 5 AND 60 AND ((booking_type='CASUAL' AND series_id IS NULL) OR (booking_type='RECURRING_OCCURRENCE' AND series_id IS NOT NULL)) AND status IN ('AWAITING_TRANSFER','AWAITING_OWNER_CONFIRMATION','NEEDS_REVIEW','CONFIRMED','EXPIRED','PAYMENT_REJECTED')");
                        });
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Bookings.BookingIdempotency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operation");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ActorUserId", "Operation", "Key")
                        .IsUnique();

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Bookings.BookingPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset?>("ConfirmationAlertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmation_alerted_at");

                    b.Property<decimal?>("ConfirmedAmount")
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("confirmed_amount");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("ExpectedAmount")
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("expected_amount");

                    b.Property<DateTimeOffset?>("FirstReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_reported_at");

                    b.Property<DateTimeOffset?>("LastReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reported_at");

                    b.Property<Guid>("PaymentScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_scope_id");

                    b.Property<Guid>("QrUploadId")
                        .HasColumnType("uuid")
                        .HasColumnName("qr_upload_id");

                    b.Property<string>("RecipientSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recipient_snapshot");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("ConfirmedBy");

                    b.HasIndex("PaymentScopeId")
                        .IsUnique();

                    b.HasIndex("QrUploadId");

                    b.HasIndex("BookingId", "PaymentScopeId");

                    b.HasIndex("FirstReportedAt", "ConfirmationAlertedAt");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_payment_confirmation", "status <> 'PAID' OR (confirmed_by IS NOT NULL AND confirmed_at IS NOT NULL AND confirmed_amount IS NOT NULL AND confirmed_amount >= 0)");

                            t.HasCheckConstraint("ck_payment_exact_amount", "status <> 'PAID' OR confirmed_amount = expected_amount");

                            t.HasCheckConstraint("ck_payment_valid", "expected_amount >= 0 AND status IN ('AWAITING_TRANSFER','TRANSFER_REPORTED','NEEDS_REVIEW','PAID','EXPIRED','REJECTED')");
                        });
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Bookings.BookingQuote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("amount");

                    b.Property<int>("BookingBlockMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("booking_block_minutes");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uuid")
                        .HasColumnName("court_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<int>("HoldMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("hold_minutes");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date")
                        .HasColumnName("local_date");

                    b.Property<TimeOnly>("LocalEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("local_end");

                    b.Property<TimeOnly>("LocalStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("local_start");

                    b.Property<int>("MinimumBookingMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_booking_minutes");

                    b.Property<string>("Slots")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("slots");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("VenueId");

                    b.ToTable("booking_quotes", null, t =>
                        {
                            t.HasCheckConstraint("ck_booking_quote_interval", "ends_at > starts_at AND amount >= 0 AND expires_at > created_at");
                        });
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Bookings.BookingSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uuid")
                        .HasColumnName("court_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<TimeOnly>("LocalStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("local_start");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("integer")
                        .HasColumnName("occurrence_count");

                    b.Property<string>("PaymentPlan")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("payment_plan");

                    b.Property<string>("SeriesNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("series_no");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SeriesNo")
                        .IsUnique();

                    b.HasIndex("CourtId", "VenueId");

                    b.ToTable("booking_series", null, t =>
                        {
                            t.HasCheckConstraint("ck_series_valid", "ends_on >= (starts_on + INTERVAL '1 month')::date AND day_of_week BETWEEN 0 AND 6 AND duration_minutes >= 120 AND MOD(duration_minutes,30)=0 AND occurrence_count BETWEEN 1 AND 12 AND amount >= 0 AND payment_plan='FULL_SERIES'");
                        });
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Bookings.BookingSeriesQuote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uuid")
                        .HasColumnName("court_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<TimeOnly>("LocalStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("local_start");

                    b.Property<string>("Occurrences")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("occurrences");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("VenueId");

                    b.ToTable("booking_series_quotes", null, t =>
                        {
                            t.HasCheckConstraint("ck_series_quote_valid", "ends_on >= (starts_on + INTERVAL '1 month')::date AND day_of_week BETWEEN 0 AND 6 AND duration_minutes >= 120 AND MOD(duration_minutes,30)=0 AND amount >= 0 AND expires_at > created_at");
                        });
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Bookings.PaymentDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("BankReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bank_reference");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<decimal?>("ConfirmedAmount")
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("confirmed_amount");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reason_code");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("resolution");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("PaymentId", "BookingId");

                    b.HasIndex("PaymentId", "DecidedAt", "Id");

                    b.ToTable("payment_decisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_decision_valid", "(resolution='CONFIRMED' AND confirmed_amount IS NOT NULL AND confirmed_amount >= 0) OR (resolution IN ('NEEDS_REVIEW','FINAL_REJECTION') AND reason_code IS NOT NULL AND reason IS NOT NULL AND length(btrim(reason))>0)");
                        });
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Bookings.PaymentEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BankReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bank_reference");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<Guid?>("ProofUploadId")
                        .HasColumnType("uuid")
                        .HasColumnName("proof_upload_id");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex("ProofUploadId")
                        .IsUnique()
                        .HasFilter("proof_upload_id IS NOT NULL");

                    b.HasIndex("PaymentId", "BookingId");

                    b.HasIndex("BookingId", "CustomerId", "VenueId");

                    b.HasIndex("PaymentId", "ReportedAt", "Id");

                    b.ToTable("payment_evidence", null, t =>
                        {
                            t.HasCheckConstraint("ck_evidence_kind", "kind IN ('INITIAL','SUPPLEMENT')");
                        });
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Identity.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId", "CreatedAt");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Identity.ContactVerificationChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("contact_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("InvalidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ContactType")
                        .IsUnique()
                        .HasDatabaseName("ux_verification_challenges_one_active")
                        .HasFilter("consumed_at IS NULL AND invalidated_at IS NULL");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_verification_challenges_user_created");

                    b.ToTable("contact_verification_challenges", (string)null);
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Identity.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("refresh_sessions", (string)null);
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("account_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedPhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("normalized_phone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("PhoneVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("phone_verified_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email")
                        .HasFilter("normalized_email IS NOT NULL");

                    b.HasIndex("NormalizedPhone")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_phone")
                        .HasFilter("normalized_phone IS NOT NULL");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_exactly_one_contact", "(normalized_email IS NOT NULL) <> (normalized_phone IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.ApprovalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("SubmittedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("SubmittedBy");

                    b.HasIndex("VenueId");

                    b.HasIndex("BusinessId", "Status");

                    b.ToTable("approval_requests", (string)null);
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("contact");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("businesses", (string)null);
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.BusinessMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId", "UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "Role", "Status");

                    b.ToTable("business_memberships", (string)null);
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BookingBlockMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("booking_block_minutes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("HoldMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("hold_minutes");

                    b.Property<int>("MinimumBookingMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_booking_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("VenueId", "Name")
                        .IsUnique();

                    b.ToTable("courts", (string)null);
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.CourtAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uuid")
                        .HasColumnName("court_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CourtId", "StartsAt", "EndsAt");

                    b.ToTable("court_allocations", (string)null);
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.CourtMaintenance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AllocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("allocation_id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uuid")
                        .HasColumnName("court_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AllocationId")
                        .IsUnique();

                    b.HasIndex("CancelledBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CourtId", "Status", "CreatedAt");

                    b.ToTable("court_maintenance", (string)null);
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.CourtOperatingHour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly>("ClosesAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("closes_at");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uuid")
                        .HasColumnName("court_id");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("OpensAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("opens_at");

                    b.HasKey("Id");

                    b.HasIndex("CourtId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("court_operating_hours", (string)null);
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.MediaUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("object_key");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("purpose");

                    b.Property<string>("Sha256Base64")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sha256_base64");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex("ObjectKey")
                        .IsUnique();

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("VenueId");

                    b.HasIndex("BookingId", "OwnerUserId", "VenueId");

                    b.HasIndex("Id", "BookingId", "OwnerUserId", "VenueId")
                        .IsUnique();

                    b.ToTable("media_uploads", null, t =>
                        {
                            t.HasCheckConstraint("ck_media_booking_purpose", "(purpose='PAYMENT_PROOF' AND booking_id IS NOT NULL) OR (purpose IN ('QR','VENUE_IMAGE') AND booking_id IS NULL)");
                        });
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OutboxMessageId", "UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AlertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alerted_at");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastFailureType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_failure_type");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id");

                    b.HasKey("Id");

                    b.HasIndex("TargetUserId");

                    b.HasIndex("ProcessedAt", "NextAttemptAt");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.PricingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uuid")
                        .HasColumnName("court_id");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("ends_at");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<long>("PricePerSlot")
                        .HasColumnType("bigint")
                        .HasColumnName("price_per_slot");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<TimeOnly>("StartsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("starts_at");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.HasKey("Id");

                    b.HasIndex("CourtId", "DayOfWeek", "StartsOn", "EndsOn", "StartsAt", "EndsAt", "Priority")
                        .IsUnique();

                    b.ToTable("pricing_rules", (string)null);
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("address");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("contact");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ImageUploadId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_upload_id");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.VenuePaymentAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("account_name");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("account_number");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("bank_code");

                    b.Property<Guid>("QrUploadId")
                        .HasColumnType("uuid")
                        .HasColumnName("qr_upload_id");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex("VenueId")
                        .IsUnique();

                    b.ToTable("venue_payment_accounts", (string)null);
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Bookings.Booking", b =>
                {
                    b.HasOne("ShuttleBook.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShuttleBook.Infrastructure.Onboarding.CourtAllocation", null)
                        .WithMany()
                        .HasForeignKey("AllocationId", "CourtId")
                        .HasPrincipalKey("Id", "CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShuttleBook.Infrastructure.Onboarding.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtId", "VenueId")
                        .HasPrincipalKey("Id", "VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShuttleBook.Infrastructure.Bookings.BookingSeries", null)
                        .WithMany()
                        .HasForeignKey("SeriesId", "CustomerId", "VenueId", "CourtId")
                        .HasPrincipalKey("Id", "CustomerId", "VenueId", "CourtId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Bookings.BookingIdempotency", b =>
                {
                    b.HasOne("ShuttleBook.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShuttleBook.Infrastructure.Bookings.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Bookings.BookingPayment", b =>
                {
                    b.HasOne("ShuttleBook.Infrastructure.Bookings.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShuttleBook.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ConfirmedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShuttleBook.Infrastructure.Onboarding.MediaUpload", null)
                        .WithMany()
                        .HasForeignKey("QrUploadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShuttleBook.Infrastructure.Bookings.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId", "PaymentScopeId")
                        .HasPrincipalKey("Id", "PaymentScopeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Bookings.BookingQuote", b =>
                {
                    b.HasOne("ShuttleBook.Infrastructure.Onboarding.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShuttleBook.Infrastructure.Onboarding.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Bookings.BookingSeries", b =>
                {
                    b.HasOne("ShuttleBook.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShuttleBook.Infrastructure.Onboarding.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtId", "VenueId")
                        .HasPrincipalKey("Id", "VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Bookings.BookingSeriesQuote", b =>
                {
                    b.HasOne("ShuttleBook.Infrastructure.Onboarding.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShuttleBook.Infrastructure.Onboarding.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Bookings.PaymentDecision", b =>
                {
                    b.HasOne("ShuttleBook.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShuttleBook.Infrastructure.Bookings.BookingPayment", null)
                        .WithMany()
                        .HasForeignKey("PaymentId", "BookingId")
                        .HasPrincipalKey("Id", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Bookings.PaymentEvidence", b =>
                {
                    b.HasOne("ShuttleBook.Infrastructure.Onboarding.MediaUpload", null)
                        .WithMany()
                        .HasForeignKey("ProofUploadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShuttleBook.Infrastructure.Bookings.BookingPayment", null)
                        .WithMany()
                        .HasForeignKey("PaymentId", "BookingId")
                        .HasPrincipalKey("Id", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShuttleBook.Infrastructure.Bookings.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId", "CustomerId", "VenueId")
                        .HasPrincipalKey("Id", "CustomerId", "VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Identity.ContactVerificationChallenge", b =>
                {
                    b.HasOne("ShuttleBook.Infrastructure.Identity.User", "User")
                        .WithMany("VerificationChallenges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Identity.RefreshSession", b =>
                {
                    b.HasOne("ShuttleBook.Infrastructure.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.ApprovalRequest", b =>
                {
                    b.HasOne("ShuttleBook.Infrastructure.Onboarding.Business", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShuttleBook.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShuttleBook.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("SubmittedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShuttleBook.Infrastructure.Onboarding.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.BusinessMembership", b =>
                {
                    b.HasOne("ShuttleBook.Infrastructure.Onboarding.Business", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShuttleBook.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.Court", b =>
                {
                    b.HasOne("ShuttleBook.Infrastructure.Onboarding.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.CourtAllocation", b =>
                {
                    b.HasOne("ShuttleBook.Infrastructure.Onboarding.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.CourtMaintenance", b =>
                {
                    b.HasOne("ShuttleBook.Infrastructure.Onboarding.CourtAllocation", null)
                        .WithMany()
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShuttleBook.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CancelledBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShuttleBook.Infrastructure.Onboarding.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShuttleBook.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.CourtOperatingHour", b =>
                {
                    b.HasOne("ShuttleBook.Infrastructure.Onboarding.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.MediaUpload", b =>
                {
                    b.HasOne("ShuttleBook.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShuttleBook.Infrastructure.Onboarding.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShuttleBook.Infrastructure.Bookings.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId", "OwnerUserId", "VenueId")
                        .HasPrincipalKey("Id", "CustomerId", "VenueId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.Notification", b =>
                {
                    b.HasOne("ShuttleBook.Infrastructure.Onboarding.OutboxMessage", null)
                        .WithMany()
                        .HasForeignKey("OutboxMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShuttleBook.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.OutboxMessage", b =>
                {
                    b.HasOne("ShuttleBook.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.PricingRule", b =>
                {
                    b.HasOne("ShuttleBook.Infrastructure.Onboarding.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.Venue", b =>
                {
                    b.HasOne("ShuttleBook.Infrastructure.Onboarding.Business", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Onboarding.VenuePaymentAccount", b =>
                {
                    b.HasOne("ShuttleBook.Infrastructure.Onboarding.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ShuttleBook.Infrastructure.Identity.User", b =>
                {
                    b.Navigation("VerificationChallenges");
                });
#pragma warning restore 612, 618
        }
    }
}
